# Generated by Django 4.1.1 on 2022-09-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_admin_date_joined_admin_groups_admin_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
