# Generated by Django 4.1.1 on 2022-09-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_alter_admin_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
