# Generated by Django 4.1.1 on 2022-09-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_admin_fullname_admin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
    ]
